<a href="https://colab.research.google.com/github/rodrigo103/AprendizajeAutomatico/blob/main/TP1_clasificaci%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Librerías de análisis de datos

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# from pandas.api.types import CategoricalDtype

from pandas.plotting import scatter_matrix

from pprint import pprint

In [ ]:
# Librerías de Machine Learning

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import PowerTransformer
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBRegressor
from xgboost import XGBClassifier

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!pwd

/content


In [ ]:
!ls drive/MyDrive/AprendizajeAutomatico

'Copia de Copia de TP1.ipynb'		       OnlineNewsPopularity.names
 online-news_Fernandes-Vinagre-Sernadela.pdf   TP1-1.ipynb
 OnlineNewsPopularity.csv		       TP1.ipynb


In [ ]:
df = pd.read_csv("drive/MyDrive/AprendizajeAutomatico/OnlineNewsPopularity.csv", sep=', ') # agregué el espacio, se estaban parceando con un espacio las keys
df.describe()

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)


timedelta  n_tokens_title  n_tokens_content  n_unique_tokens  \
count  39644.000000    39644.000000      39644.000000     39644.000000   
mean     354.530471       10.398749        546.514731         0.548216   
std      214.163767        2.114037        471.107508         3.520708   
min        8.000000        2.000000          0.000000         0.000000   
25%      164.000000        9.000000        246.000000         0.470870   
50%      339.000000       10.000000        409.000000         0.539226   
75%      542.000000       12.000000        716.000000         0.608696   
max      731.000000       23.000000       8474.000000       701.000000   

       n_non_stop_words  n_non_stop_unique_tokens     num_hrefs  \
count      39644.000000              39644.000000  39644.000000   
mean           0.996469                  0.689175     10.883690   
std            5.231231                  3.264816     11.332017   
min            0.000000                  0.000000      0.000000   
25%            1.000000                  0.625739      4.000000   
50%            1.000000                  0.690476      8.000000   
75%            1.000000                  0.754630     14.000000   
max         1042.000000                650.000000    304.000000   

       num_self_hrefs      num_imgs    num_videos  ...  min_positive_polarity  \
count    39644.000000  39644.000000  39644.000000  ...           39644.000000   
mean         3.293638      4.544143      1.249874  ...               0.095446   
std          3.855141      8.309434      4.107855  ...               0.071315   
min          0.000000      0.000000      0.000000  ...               0.000000   
25%          1.000000      1.000000      0.000000  ...               0.050000   
50%          3.000000      1.000000      0.000000  ...               0.100000   
75%          4.000000      4.000000      1.000000  ...               0.100000   
max        116.000000    128.000000     91.000000  ...               1.000000   

       max_positive_polarity  avg_negative_polarity  min_negative_polarity  \
count           39644.000000           39644.000000           39644.000000   
mean                0.756728              -0.259524              -0.521944   
std                 0.247786               0.127726               0.290290   
min                 0.000000              -1.000000              -1.000000   
25%                 0.600000              -0.328383              -0.700000   
50%                 0.800000              -0.253333              -0.500000   
75%                 1.000000              -0.186905              -0.300000   
max                 1.000000               0.000000               0.000000   

       max_negative_polarity  title_subjectivity  title_sentiment_polarity  \
count           39644.000000        39644.000000              39644.000000   
mean               -0.107500            0.282353                  0.071425   
std                 0.095373            0.324247                  0.265450   
min                -1.000000            0.000000                 -1.000000   
25%                -0.125000            0.000000                  0.000000   
50%                -0.100000            0.150000                  0.000000   
75%                -0.050000            0.500000                  0.150000   
max                 0.000000            1.000000                  1.000000   

       abs_title_subjectivity  abs_title_sentiment_polarity         shares  
count            39644.000000                  39644.000000   39644.000000  
mean                 0.341843                      0.156064    3395.380184  
std                  0.188791                      0.226294   11626.950749  
min                  0.000000                      0.000000       1.000000  
25%                  0.166667                      0.000000     946.000000  
50%                  0.500000                      0.000000    1400.000000  
75%                  0.500000                      0.250000    2

Corriendo el siguiente código puedo generar la columna de los target para la claficación.

In [ ]:
def get_label(share):
  if share <= 870:
    return 'Very Poor'
  elif share <= 1200:
    return 'Poor'
  elif share <= 1800:
    return 'Average'
  elif share <= 3400:
    return 'Good'
  else:
    return 'Very Good'

df['shares_clasif'] = df['shares'].apply(get_label)
df

NameError: ignored

# Clasificación
Entreno los modelos de clasificación usando la misma configuración que para regresión. Los modelos son los mismos pero en su versión para clasificación.

In [ ]:
features = [
    # 'timedelta', 
    # Words
    'n_tokens_title', 'n_tokens_content', 
    # 'average_token_length', 
    # 'n_unique_tokens', 'n_non_stop_words', 'n_non_stop_unique_tokens',
    'num_hrefs', 'num_self_hrefs',
    # Digital Media
    # 'num_imgs', 'num_videos', 
    # Links
    'self_reference_min_shares', 'self_reference_max_shares', 'self_reference_avg_sharess', 
    # Time
    # 'weekday_is_monday', 'weekday_is_tuesday', 'weekday_is_wednesday', 'weekday_is_thursday', 'weekday_is_friday', 'weekday_is_saturday', 'weekday_is_sunday', 
    # 'is_weekend', 
    # Keywords
    'num_keywords', 
    'kw_min_min', 'kw_max_min', 'kw_avg_min', 'kw_min_max', 'kw_max_max', 'kw_avg_max', 'kw_min_avg', 'kw_max_avg', 'kw_avg_avg', 
    'data_channel_is_lifestyle', 'data_channel_is_entertainment', 'data_channel_is_bus', 'data_channel_is_socmed', 'data_channel_is_tech', 'data_channel_is_world', 
    # Natural Language Processing
    'LDA_00', 'LDA_01', 'LDA_02', 'LDA_03', 'LDA_04', 
    'global_subjectivity', 'global_sentiment_polarity', 
    'global_rate_positive_words', 'global_rate_negative_words', 
    'rate_positive_words', 'rate_negative_words', 
    'avg_positive_polarity', 'min_positive_polarity', 'max_positive_polarity', 
    'avg_negative_polarity', 'min_negative_polarity', 'max_negative_polarity', 
    'title_subjectivity', 'title_sentiment_polarity', 'abs_title_subjectivity', 'abs_title_sentiment_polarity'
]

X = df[features]
y = df.shares_clasif

train_X, val_X, train_y, val_y = train_test_split(X, y, random_state = 0)


# Funcion para comparar distintos modelos
def score_model(model, X_t=train_X, X_v=val_X, y_t=train_y, y_v=val_y):
    model.fit(X_t, y_t)
    preds = model.predict(X_v)
    return accuracy_score(y_v, preds)

models = [
    DecisionTreeClassifier(max_leaf_nodes=None, random_state=1),
    DecisionTreeClassifier(max_leaf_nodes=2, random_state=1),
    DecisionTreeClassifier(max_leaf_nodes=3, random_state=1),
    DecisionTreeClassifier(max_leaf_nodes=4, random_state=1),
    DecisionTreeClassifier(max_leaf_nodes=5, random_state=1),
    DecisionTreeClassifier(max_leaf_nodes=6, random_state=1),
    DecisionTreeClassifier(max_leaf_nodes=7, random_state=1),
    DecisionTreeClassifier(max_leaf_nodes=8, random_state=1),
    DecisionTreeClassifier(max_leaf_nodes=9, random_state=1),
    DecisionTreeClassifier(max_leaf_nodes=10, random_state=1),
    DecisionTreeClassifier(max_leaf_nodes=20, random_state=1),
    DecisionTreeClassifier(max_leaf_nodes=30, random_state=1),
    DecisionTreeClassifier(max_leaf_nodes=40, random_state=1),
    DecisionTreeClassifier(max_leaf_nodes=50, random_state=1),
    DecisionTreeClassifier(max_leaf_nodes=500, random_state=1),
    DecisionTreeClassifier(max_leaf_nodes=5000, random_state=1),
    RandomForestClassifier(random_state=1),
    RandomForestClassifier(n_estimators=50, random_state=1),
    RandomForestClassifier(n_estimators=100, random_state=1),
    # RandomForestClassifier(n_estimators=100, criterion='absolute_error', random_state=1),
    # RandomForestClassifier(n_estimators=200, min_samples_split=20, random_state=1),
    # RandomForestClassifier(n_estimators=100, max_depth=7, random_state=1),
    XGBClassifier(), 
    XGBClassifier(n_estimators=500), 
    XGBClassifier(n_estimators=1000, learning_rate=0.05),
]

for i in range(0, len(models)):
    acc = score_model(models[i])
    print("Model %d Accuracy: %f" % (i+1, acc))

# Pruebo usando early stopping
my_model2 = XGBClassifier(n_estimators=500)
my_model2.fit(train_X, train_y,
              early_stopping_rounds=5, 
             eval_set=[(val_X, val_y)],
             verbose=False)
preds = my_model2.predict(val_X)
print("Accuracy: " + str(accuracy_score(preds, val_y)))

Model 1 Accuracy: 0.248007
Model 2 Accuracy: 0.267985
Model 3 Accuracy: 0.271113
Model 4 Accuracy: 0.276662
Model 5 Accuracy: 0.276662
Model 6 Accuracy: 0.279588
Model 7 Accuracy: 0.279588
Model 8 Accuracy: 0.278882
Model 9 Accuracy: 0.283120
Model 10 Accuracy: 0.283120
Model 11 Accuracy: 0.288871
Model 12 Accuracy: 0.293008
Model 13 Accuracy: 0.293916
Model 14 Accuracy: 0.294219
Model 15 Accuracy: 0.284028
Model 16 Accuracy: 0.250126
Model 17 Accuracy: 0.301786
Model 18 Accuracy: 0.290990
Model 19 Accuracy: 0.301786
Model 20 Accuracy: 0.316214
Model 21 Accuracy: 0.314600
Model 22 Accuracy: 0.314398
Accuracy: 0.29805266875189185


La mejor precisión observada es de 0.318 para el modelo 20, que es el XGBClassifier() sin parámetros. Esta precisión supera la linea de base aleatoria de 0.2.

Para ese modelo vamos a calcular y mostrar las matrices de confusion.

In [ ]:
my_model2 = XGBClassifier()
my_model2.fit(train_X, train_y)
preds = my_model2.predict(val_X)
print("Accuracy: " + str(accuracy_score(preds, val_y)))


confusion = confusion_matrix(val_y, preds)
print(f"Confusion matrix:\n{confusion}")

print(f"\nNormalized confusion matrix:")
for row in confusion:
    print(row / row.sum())


print(f"\nProbs:")
probs = my_model2.predict_proba(val_X)
print(probs)


print(f"\nClassification report:")
report = classification_report(val_y, preds)
print(report)

Accuracy: 0.31621430733528405
Confusion matrix:
[[147 349 528 496 369]
 [159 415 372 574 297]
 [137 243 753 441 666]
 [107 355 291 925 268]
 [ 84 127 602 312 894]]

Normalized confusion matrix:
[0.07781895 0.18475384 0.27951297 0.26257279 0.19534145]
[0.08750688 0.22839846 0.20473308 0.31590534 0.16345625]
[0.06116071 0.10848214 0.33616071 0.196875   0.29732143]
[0.05498458 0.18242549 0.14953751 0.47533402 0.1377184 ]
[0.04160475 0.06290243 0.29816741 0.15453195 0.44279346]

Probs:
[[0.20386672 0.10750477 0.34347168 0.0690873  0.27606955]
 [0.17825504 0.23596886 0.2241451  0.15964583 0.20198514]
 [0.28839678 0.27310723 0.1894298  0.15224674 0.09681943]
 ...
 [0.20587832 0.10839653 0.3830459  0.06823114 0.23444806]
 [0.2515199  0.3312027  0.13662685 0.1909773  0.08967327]
 [0.172007   0.12765108 0.2947282  0.10166623 0.3039475 ]]

Classification report:
              precision    recall  f1-score   support

     Average       0.23      0.08      0.12      1889
        Good       0.28   

Probamos si valores numéricos para la columna de clasificación funcionan mejor

In [ ]:
def get_label2(share):
  if share == 'Very Poor':
    return 0
  elif share == 'Poor':
    return 1
  elif share == 'Average':
    return 2
  elif share == 'Good':
    return 3
  else:
    return 4

df['shares_clasif'] = df['shares_clasif'].apply(get_label2)
df

url  timedelta  \
0      http://mashable.com/2013/01/07/amazon-instant-...      731.0   
1      http://mashable.com/2013/01/07/ap-samsung-spon...      731.0   
2      http://mashable.com/2013/01/07/apple-40-billio...      731.0   
3      http://mashable.com/2013/01/07/astronaut-notre...      731.0   
4       http://mashable.com/2013/01/07/att-u-verse-apps/      731.0   
...                                                  ...        ...   
39639  http://mashable.com/2014/12/27/samsung-app-aut...        8.0   
39640  http://mashable.com/2014/12/27/seth-rogen-jame...        8.0   
39641  http://mashable.com/2014/12/27/son-pays-off-mo...        8.0   
39642     http://mashable.com/2014/12/27/ukraine-blasts/        8.0   
39643  http://mashable.com/2014/12/27/youtube-channel...        8.0   

       n_tokens_title  n_tokens_content  n_unique_tokens  n_non_stop_words  \
0                12.0             219.0         0.663594               1.0   
1                 9.0             255.0         0.604743               1.0   
2                 9.0             211.0         0.575130               1.0   
3                 9.0             531.0         0.503788               1.0   
4                13.0            1072.0         0.415646               1.0   
...               ...               ...              ...               ...   
39639            11.0             346.0         0.529052               1.0   
39640            12.0             328.0         0.696296               1.0   
39641            10.0             442.0         0.516355               1.0   
39642             6.0             682.0         0.539493               1.0   
39643            10.0             157.0         0.701987               1.0   

       n_non_stop_unique_tokens  num_hrefs  num_self_hrefs  num_imgs  ...  \
0                      0.815385        4.0             2.0       1.0  ...   
1                      0.791946        3.0             1.0       1.0  ...   
2                      0.663866        3.0             1.0       1.0  ...   
3                      0.665635        9.0             0.0       1.0  ...   
4                      0.540890       19.0            19.0      20.0  ...   
...                         ...        ...             ...       ...  ...   
39639                  0.684783        9.0             7.0       1.0  ...   
39640                  0.885057        9.0             7.0       3.0  ...   
39641                  0.644128       24.0             1.0      12.0  ...   
39642                  0.692661       10.0             1.0       1.0  ...   
39643                  0.846154        1.0             1.0       0.0  ...   

       max_positive_polarity  avg_negative_polarity  min_negative_polarity  \
0                       0.70              -0.350000                 -0.600   
1                       0.70              -0.118750                 -0.125   
2                       1.00              -0.466667                 -0.800   
3                       0.80              -0.369697                 -0.600   
4                       1.00              -0.220192                 -0.500   
...                      ...                    ...                    ...   
39639                   0.75              -0.260000                 -0.500   
39640                   0.70              -0.211111                 -0.400   
39641                   0.50              -0.356439                 -0.800   
39642                   0.50              -0.205246                 -0.500   
39643                   0.50              -0.200000                 -0.200   

       max_negative_polarity  title_subjectivity  title_sentiment_polarity  \
0                  -0.200000            0.500000                 -0.187500   
1                  -0.100000            0.000000                  0.000000   
2                  -0.133333            0.000000                  0.000000   
3                  -0.166667            0.000000                  0.000000   
4          

In [ ]:
X = df[features]
y = df.shares_clasif

train_X, val_X, train_y, val_y = train_test_split(X, y, random_state = 0)


my_model2 = XGBClassifier()
my_model2.fit(train_X, train_y)
preds = my_model2.predict(val_X)
print("Accuracy: " + str(accuracy_score(preds, val_y)))


confusion = confusion_matrix(val_y, preds)
print(f"Confusion matrix:\n{confusion}")

print(f"\nNormalized confusion matrix:")
for row in confusion:
    print(row / row.sum())


print(f"\nProbs:")
probs = my_model2.predict_proba(val_X)
print(probs)


print(f"\nClassification report:")
report = classification_report(val_y, preds)
print(report)

Accuracy: 0.31621430733528405
Confusion matrix:
[[894 602  84 127 312]
 [666 753 137 243 441]
 [369 528 147 349 496]
 [297 372 159 415 574]
 [268 291 107 355 925]]

Normalized confusion matrix:
[0.44279346 0.29816741 0.04160475 0.06290243 0.15453195]
[0.29732143 0.33616071 0.06116071 0.10848214 0.196875  ]
[0.19534145 0.27951297 0.07781895 0.18475384 0.26257279]
[0.16345625 0.20473308 0.08750688 0.22839846 0.31590534]
[0.1377184  0.14953751 0.05498458 0.18242549 0.47533402]

Probs:
[[0.27606955 0.34347168 0.20386672 0.10750477 0.0690873 ]
 [0.20198514 0.2241451  0.17825504 0.23596886 0.15964583]
 [0.09681943 0.1894298  0.28839678 0.27310723 0.15224674]
 ...
 [0.23444806 0.3830459  0.20587832 0.10839653 0.06823114]
 [0.08967327 0.13662685 0.2515199  0.3312027  0.1909773 ]
 [0.3039475  0.2947282  0.172007   0.12765108 0.10166623]]

Classification report:
              precision    recall  f1-score   support

           0       0.36      0.44      0.40      2019
           1       0.30   

Los valores de accuracy resultan ser iguales, pero no los de precision, recall, f1-score y support